version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/wordpress/


hooks:
   Afterinstall:
         - location: /script/afterinstall.sh
           timeout: 500
           runas: root

   ApplicationStop:
         - location: /script/stop_script.sh
           timeout: 300
           runas: root

   ApplicationStart:
         - location: /script/start_script.sh
           timeout: 300
           runas: root 
