version: 0.2

env:
   parameter-store:
           DB_Name: "/kamal/db_name"
           DB_User: "/kamal/db_user"
           DB_Password: "/kamal/db_password"
           DB_Host: "/kamal/db_host"


   

               
phases:
   build:
        commands:
            - sed -i 's/database_name_here/'$DB_Name'/' wp-config.php
            - sed -i 's/username_here/'$DB_User'/' wp-config.php
            - sed -i 's/password_here/'$DB_Password'/' wp-config.php
            - sed -i 's/localhost/'$DB_Host'/' wp-config.php
            
artifacts:
        files:
            - '**/*'
